[package]
name = "membrs-frontend"
version = "0.1.0"
publish = false
edition = "2021"
authors = ["Arteii <ben.arteii@proton.me>"]
license = "AGPL-3"
readme = "README.md"

[[bin]]
name = "frontend"
path = "src/main.rs"

[dependencies]
