services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - target: 80
        published: ${PORT}
        mode: host
#      - target: 443
#        published: 443
#        mode: host
    restart: unless-stopped
    networks:
      - backend
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        DOCKER_BUILDKIT: 1
    container_name: membrs-backend
    restart: unless-stopped
    expose:
      - "8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: db
      BACKEND_URL: ${URL}/api
      FRONTEND_URL: ${URL}/
      RUST_LOG: DEBUG
    networks:
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        BASE_URL: ${URL}:${PORT}
    container_name: membrs-frontend
    depends_on:
      - backend
    expose:
      - "3000"
    networks:
      - frontend

  db:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:6500"
    healthcheck:
      test: "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - backend

networks:
  backend:
    external: false
  frontend:
    external: false

volumes:
  postgres-data:
