services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - target: 80
        published: ${PORT}
        mode: host
#      - target: 443
#        published: 443
#        mode: host
    restart: unless-stopped
    networks:
      - backend
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    healthcheck:
      test: [ "CMD", "curl", "-k", "https://google.com/" ]
      interval: 20s
      timeout: 5s
      retries: 10
      start_period: 20s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: membrs-backend
    restart: unless-stopped
    expose:
      - "8000"
    depends_on:
      nginx:
        condition: service_healthy
      db:
        condition: service_healthy
    environment:
      PORT: 8000
      POSTGRES: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/membrs
      URL: ${URL}
      RUST_LOG: TRACE
    volumes:
      - crash_reports:/tmp
    networks:
      - backend


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        BASE_URL: ${URL}:${PORT}
    container_name: membrs-frontend
#    depends_on:
#      - backend
    expose:
      - "3000"
    networks:
      - frontend
    depends_on:
      nginx:
        condition: service_healthy

  db:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: membrs
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:6500"
    healthcheck:
      test: "pg_isready -U ${POSTGRES_USER} -d membrs"
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - backend

networks:
  backend:
    external: false
  frontend:
    external: false

volumes:
  postgres-data:
  crash_reports:
