version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - public_net
      - frontend_net
      - backend_net
    depends_on:
      - backend
      - frontend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        DOCKER_BUILDKIT: 1
    container_name: membrs-backend
    networks:
      - backend_net
    expose:
      - "8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: db
      BACKEND_URL: ${BACKEND_URL}
      FRONTEND_URL: ${FRONTEND_URL}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: membrs-frontend
    depends_on:
      - backend
    networks:
      - frontend_net
    expose:
      - "3000"
    environment:
      NEXT_PUBLIC_BACKEND_URL: ${BACKEND_URL}
      NEXT_PUBLIC_FRONTEND_URL: ${FRONTEND_URL}

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend_net
    ports:
      - "6500:${POSTGRES_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10

networks:
  public_net:
    driver: bridge
  frontend_net:
    driver: bridge
  backend_net:
    driver: bridge

volumes:
  postgres-data:
